services:
  serilovers.api:
    build: .
    container_name: serilovers.api
    ports:
      - "5149:5149"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=serilovers.db;Database=IB220036;User Id=sa;Password=YourStrong!Pass;TrustServerCertificate=True;"
      JwtSettings__SecretKey: "YourDockerSuperSecretKeyThatIsAtLeast32Characters!"
      JwtSettings__Issuer: "SeriLovers.API"
      JwtSettings__Audience: "SeriLovers.API"
      RabbitMq__Connection: "host=rabbitmq;username=guest;password=guest"
    depends_on:
      - serilovers.db
      - rabbitmq

  serilovers.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: serilovers.db
    environment:
      SA_PASSWORD: "YourStrong!Pass"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - serilovers-data:/var/opt/mssql

  serilovers.worker:
    build:
      context: .
      dockerfile: SeriLovers.Worker/Dockerfile
    container_name: serilovers.worker
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=serilovers.db;Database=IB220036;User Id=sa;Password=YourStrong!Pass;TrustServerCertificate=True;"
      RabbitMq__Connection: "host=rabbitmq;username=guest;password=guest"
    depends_on:
      - serilovers.db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: serilovers.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  serilovers-data:
  rabbitmq-data:
